language: scala
jdk:
  - oraclejdk8

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - stage: test
      script: 
        - sbt scalafmtCheckAll scalafmtSbtCheck
        - sbt +test
      name: "Cross version tests and scalafmt check"
    - stage: release
      script: sbt -Dsbt.gigahorse=false ci-release publishMicrosite
      name: "Release to sonatype"

after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  scripts/publishMicrosite.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping
  deploy and release"; fi

cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier
    - $HOME/.rvm/
    - vendor/bundle

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local

before_install:
  - git fetch --tags
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.3.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.8.3